server {
    listen 80;
    server_name api.bovino.agr.br;
    root /var/www/bovino/api/public;
    index index.php;

    client_max_body_size 50M;

    # Logs
    access_log /var/log/nginx/bovino_api_access.log;
    error_log  /var/log/nginx/bovino_api_error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 300;
    }

    location ~ /\.ht {
        deny all;
    }

    location ~ /\.env {
        deny all;
    }
}
