<?php

namespace Database\Seeders;

use App\Models\Plano;
use Illuminate\Database\Seeder;

class PlanoSeeder extends Seeder
{
    public function run(): void
    {
        $planos = [
            // ── COMPRADORES ──────────────────────────────────────────────
            [
                'slug' => 'comprador-premium',
                'nome' => 'Comprador Premium',
                'tipo' => 'comprador',
                'preco' => 200.00,
                'periodo' => 'mensal',
                'ordem' => 1,
                'max_anuncios' => 0,
                'max_destaques' => 0,
                'ver_contato_vendedor' => true,
                'alertas_preco' => true,
                'analytics' => true,
                'badge_verificado' => true,
                'suporte_prioritario' => false,
                'recursos' => [
                    'Ver WhatsApp e telefone do vendedor',
                    'Alertas de preço por raça e região',
                    'Histórico completo de cotações (30 dias)',
                    'Favoritos ilimitados',
                    'Badge "Comprador Verificado"',
                    'Filtros avançados de busca',
                    'Inteligência de mercado: preços por raça e região',
                    'Mapa de oferta: onde encontrar cada raça',
                    'Ranking de regiões com melhor preço',
                    'Oportunidades: anúncios abaixo da média',
                    'Tendência de preços (últimos 30 dias)',
                    'Alerta de oportunidade de compra',
                ],
            ],

            // ── PRODUTORES ────────────────────────────────────────────────
            [
                'slug' => 'produtor-basico',
                'nome' => 'Produtor Básico',
                'tipo' => 'produtor',
                'preco' => 50.00,
                'periodo' => 'mensal',
                'ordem' => 1,
                'max_anuncios' => 15,
                'max_destaques' => 2,
                'ver_contato_vendedor' => false,
                'alertas_preco' => false,
                'analytics' => false,
                'badge_verificado' => false,
                'suporte_prioritario' => false,
                'recursos' => [
                    'Até 15 anúncios ativos',
                    '2 anúncios em destaque por mês',
                    'Fotos e vídeos nos anúncios',
                    'Chat com compradores',
                    'Suporte por e-mail',
                ],
            ],
            [
                'slug' => 'produtor-premium',
                'nome' => 'Produtor Premium',
                'tipo' => 'produtor',
                'preco' => 100.00,
                'periodo' => 'mensal',
                'ordem' => 2,
                'max_anuncios' => 50,
                'max_destaques' => 10,
                'ver_contato_vendedor' => false,
                'alertas_preco' => true,
                'analytics' => true,
                'badge_verificado' => true,
                'suporte_prioritario' => false,
                'recursos' => [
                    'Até 50 anúncios ativos',
                    '10 anúncios em destaque por mês',
                    'Badge "Produtor Verificado"',
                    'Página de fazenda (mini-site público)',
                    'Gestão de rebanho (até 200 animais)',
                    'Gestão de lotes + publicação direta',
                    'Saúde animal: vacinas e vermifugação',
                    'Controle de pesagens e GMD',
                    'Financeiro básico por lote',
                    'Inteligência de mercado: demanda por região',
                    'Alertas quando comprador busca seu perfil (5 alertas)',
                    'Agendamento de visitas aos anúncios',
                    'Analytics de visualizações por anúncio',
                    'Suporte por WhatsApp',
                ],
            ],
            [
                'slug' => 'produtor-elite',
                'nome' => 'Produtor Elite',
                'tipo' => 'produtor',
                'preco' => 200.00,
                'periodo' => 'mensal',
                'ordem' => 3,
                'max_anuncios' => 0,
                'max_destaques' => 20,
                'ver_contato_vendedor' => false,
                'alertas_preco' => true,
                'analytics' => true,
                'badge_verificado' => true,
                'suporte_prioritario' => true,
                'recursos' => [
                    'Anúncios ilimitados',
                    '20 anúncios em destaque por mês',
                    'Badge "Produtor Elite"',
                    'Página de fazenda com avaliações verificadas',
                    'Gestão de rebanho ilimitada + reprodução',
                    'Gerenciador de lotes completo (CRM)',
                    'Saúde animal com calendário e alertas automáticos',
                    'Pesagens com cálculo de GMD e histórico',
                    'Módulo reprodutivo (cobertura, gestação, parto)',
                    'Gestão de pastagens e lotação',
                    'Financeiro completo com relatório por lote',
                    'Cotação média paga por raça/região (30 dias)',
                    'Mapa de demanda: onde estão seus compradores',
                    'Alertas de demanda ilimitados',
                    'Agendamento de visitas com confirmação',
                    'Selo de rastreabilidade (GTA/SISBOV) no anúncio',
                    'Prioridade máxima nas buscas',
                    'Suporte prioritário 7 dias por semana',
                ],
            ],

            // ── ANUNCIANTES ───────────────────────────────────────────────
            [
                'slug' => 'anunciante-regional',
                'nome' => 'Regional',
                'tipo' => 'anunciante',
                'preco' => 500.00,
                'periodo' => 'mensal',
                'ordem' => 1,
                'max_anuncios' => 0,
                'max_destaques' => 0,
                'ver_contato_vendedor' => false,
                'alertas_preco' => false,
                'analytics' => true,
                'badge_verificado' => false,
                'suporte_prioritario' => false,
                'recursos' => [
                    'Banner em até 2 estados',
                    '1 posição ativa (feed ou busca)',
                    'Até 50.000 impressões/mês',
                    'Relatório mensal de cliques e impressões',
                    'Painel de gerenciamento de banners',
                ],
            ],
            [
                'slug' => 'anunciante-nacional',
                'nome' => 'Nacional',
                'tipo' => 'anunciante',
                'preco' => 1000.00,
                'periodo' => 'mensal',
                'ordem' => 2,
                'max_anuncios' => 0,
                'max_destaques' => 0,
                'ver_contato_vendedor' => false,
                'alertas_preco' => false,
                'analytics' => true,
                'badge_verificado' => false,
                'suporte_prioritario' => false,
                'recursos' => [
                    'Banner nacional (todos os estados)',
                    '2 posições ativas (feed + busca)',
                    'Até 200.000 impressões/mês',
                    'Relatório semanal detalhado',
                    'Painel de gerenciamento completo',
                    'Suporte dedicado',
                ],
            ],
            [
                'slug' => 'anunciante-nacional-premium',
                'nome' => 'Nacional Premium',
                'tipo' => 'anunciante',
                'preco' => 2000.00,
                'periodo' => 'mensal',
                'ordem' => 3,
                'max_anuncios' => 0,
                'max_destaques' => 0,
                'ver_contato_vendedor' => false,
                'alertas_preco' => false,
                'analytics' => true,
                'badge_verificado' => false,
                'suporte_prioritario' => true,
                'recursos' => [
                    'Banner na homepage (posição principal)',
                    '3 posições ativas (home + feed + busca)',
                    'Até 500.000 impressões/mês',
                    'Relatório em tempo real',
                    'Banners personalizados por público-alvo',
                    'Gerente de conta dedicado',
                    'Suporte 24/7',
                ],
            ],
        ];

        foreach ($planos as $dados) {
            Plano::updateOrCreate(['slug' => $dados['slug']], $dados);
        }
    }
}
